<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ActivityLogTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('activity_log')->delete();
        
        \DB::table('activity_log')->insert(array (
            0 => 
            array (
                'id' => 1,
                'log_name' => 'default',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 1,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes": {"id": 1, "name": "Fakhrurrazi", "email": "fakhrurrazi.code@gmail.com", "photo": null, "password": "$2y$12$Oz9ZkbkNpbpX3Oescf/jM.x42H3bY1QWXRRcdRMXE5HJIdBPpoExy", "username": null, "created_at": "2025-02-03 09:03:18", "updated_at": "2025-02-03 09:03:18", "remember_token": null, "email_verified_at": null}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-02-03 09:03:18',
                'updated_at' => '2025-02-03 09:03:18',
            ),
            1 => 
            array (
                'id' => 2,
                'log_name' => 'default',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 2,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes": {"id": 2, "name": "Fakhrurrazi", "email": "fakhrurrazi.code@gmail.com", "photo": null, "password": "$2y$12$.TcDVEQ/mG1S56.M7TqLUu2JTS2Rrh/wbZSOJGYRk/VB5qFm9TJfW", "username": "fakhrurrazi.code", "created_at": "2025-02-04 02:38:07", "updated_at": "2025-02-04 02:38:07", "remember_token": null, "email_verified_at": null}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-02-04 02:38:08',
                'updated_at' => '2025-02-04 02:38:08',
            ),
            2 => 
            array (
                'id' => 3,
                'log_name' => 'default',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 3,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes": {"id": 3, "name": "Fakhrurrazi", "email": "fakhrurrazi.code@gmail.com", "photo": null, "password": "$2y$12$9Xp50JkE2j5oPSzeH9tSk.W849gxRlO8WFRAVM/YyydTHleC3tSyS", "username": "fakhrurrazi.code", "created_at": "2025-02-04 03:18:00", "updated_at": "2025-02-04 03:18:00", "remember_token": null, "email_verified_at": null}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-02-04 03:18:00',
                'updated_at' => '2025-02-04 03:18:00',
            ),
            3 => 
            array (
                'id' => 4,
                'log_name' => 'default',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 4,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes": {"id": 4, "name": "Fakhrurrazi", "email": "fakhrurrazi.code@gmail.com", "photo": null, "password": "$2y$12$E.6bu0f8eMdThCY0GulJbeNMvut1huAkSGxE3rg.fR/bOilRHjfZS", "username": "fakhrurrazi.code", "created_at": "2025-02-04 04:11:21", "updated_at": "2025-02-04 04:11:21", "remember_token": null, "email_verified_at": null}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-02-04 04:11:21',
                'updated_at' => '2025-02-04 04:11:21',
            ),
            4 => 
            array (
                'id' => 5,
                'log_name' => 'default',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 5,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 4,
                'properties' => '{"attributes": {"id": 5, "name": "Administrator", "email": "administrator@gmail.com", "photo": null, "password": "$2y$12$xmYO.X8pNRYawBiyeBvE5uzpwiS44TrVcfPrQu8TG9JllMtDfXnrS", "username": null, "created_at": "2025-02-11 02:57:57", "updated_at": "2025-02-11 02:57:57", "remember_token": null, "email_verified_at": null}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-02-11 02:57:57',
                'updated_at' => '2025-02-11 02:57:57',
            ),
            5 => 
            array (
                'id' => 6,
                'log_name' => 'default',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 6,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 4,
                'properties' => '{"attributes": {"id": 6, "name": "Instructor", "email": "instructor@gmail.com", "photo": null, "password": "$2y$12$jTBuMP55vF1ugWReREvGIuqPQ1eRWDTk05Kb1fUxm.OivgHEVf612", "username": null, "created_at": "2025-02-11 02:58:19", "updated_at": "2025-02-11 02:58:19", "remember_token": null, "email_verified_at": null}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-02-11 02:58:19',
                'updated_at' => '2025-02-11 02:58:19',
            ),
            6 => 
            array (
                'id' => 7,
                'log_name' => 'default',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 7,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 4,
                'properties' => '{"attributes": {"id": 7, "name": "Student", "email": "student@gmail.com", "photo": null, "password": "$2y$12$O/VLHJ/I90kVPccPVc8AdOC00SfxtU7igGZ52iRNrjFzeR1ujYPBm", "username": null, "created_at": "2025-02-11 02:58:36", "updated_at": "2025-02-11 02:58:36", "remember_token": null, "email_verified_at": null}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-02-11 02:58:36',
                'updated_at' => '2025-02-11 02:58:36',
            ),
            7 => 
            array (
                'id' => 8,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 7,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 7,
                'properties' => '{"old": {"id": 7, "name": "Student", "email": "student@gmail.com", "photo": null, "password": "$2y$12$O/VLHJ/I90kVPccPVc8AdOC00SfxtU7igGZ52iRNrjFzeR1ujYPBm", "username": null, "created_at": "2025-02-11 02:58:36", "updated_at": "2025-02-11 02:58:36", "remember_token": null, "email_verified_at": null}, "attributes": {"id": 7, "name": "Student", "email": "student@gmail.com", "photo": null, "password": "$2y$12$O/VLHJ/I90kVPccPVc8AdOC00SfxtU7igGZ52iRNrjFzeR1ujYPBm", "username": null, "created_at": "2025-02-11 02:58:36", "updated_at": "2025-02-11 02:58:36", "remember_token": "vrPIOYPkNmgaiOEgpbLBeLQ3fvuAmgTdSSaTV4yqQOPuyrTvfkgt65gRIb3Y", "email_verified_at": null}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-02-11 02:59:13',
                'updated_at' => '2025-02-11 02:59:13',
            ),
            8 => 
            array (
                'id' => 9,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 7,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 7,
                'properties' => '{"old": {"id": 7, "name": "Student", "email": "student@gmail.com", "photo": null, "password": "$2y$12$O/VLHJ/I90kVPccPVc8AdOC00SfxtU7igGZ52iRNrjFzeR1ujYPBm", "username": null, "created_at": "2025-02-11 02:58:36", "updated_at": "2025-02-11 02:58:36", "remember_token": "vrPIOYPkNmgaiOEgpbLBeLQ3fvuAmgTdSSaTV4yqQOPuyrTvfkgt65gRIb3Y", "email_verified_at": null}, "attributes": {"id": 7, "name": "Student", "email": "student@gmail.com", "photo": null, "password": "$2y$12$O/VLHJ/I90kVPccPVc8AdOC00SfxtU7igGZ52iRNrjFzeR1ujYPBm", "username": null, "created_at": "2025-02-11 02:58:36", "updated_at": "2025-02-11 02:58:36", "remember_token": "ahodTd6YHjWSXe826lfMiR3PFw9eRZQVwzBBddVgGb0ypn3zmhzivT8VPsOJ", "email_verified_at": null}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-02-11 03:25:19',
                'updated_at' => '2025-02-11 03:25:19',
            ),
            9 => 
            array (
                'id' => 10,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 7,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 7,
                'properties' => '{"old": {"id": 7, "name": "Student", "email": "student@gmail.com", "photo": null, "password": "$2y$12$O/VLHJ/I90kVPccPVc8AdOC00SfxtU7igGZ52iRNrjFzeR1ujYPBm", "username": null, "created_at": "2025-02-11 02:58:36", "updated_at": "2025-02-11 02:58:36", "remember_token": "ahodTd6YHjWSXe826lfMiR3PFw9eRZQVwzBBddVgGb0ypn3zmhzivT8VPsOJ", "email_verified_at": null}, "attributes": {"id": 7, "name": "Student", "email": "student@gmail.com", "photo": null, "password": "$2y$12$O/VLHJ/I90kVPccPVc8AdOC00SfxtU7igGZ52iRNrjFzeR1ujYPBm", "username": null, "created_at": "2025-02-11 02:58:36", "updated_at": "2025-02-11 02:58:36", "remember_token": "xKFl4pEB1sGeZILezdQm2AHuYLmy6BmL5J1dBkfz8g8DeOm90fm7CL1pT29W", "email_verified_at": null}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-02-11 03:32:12',
                'updated_at' => '2025-02-11 03:32:12',
            ),
            10 => 
            array (
                'id' => 11,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 7,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 7,
                'properties' => '{"old": {"id": 7, "name": "Student", "email": "student@gmail.com", "photo": null, "password": "$2y$12$O/VLHJ/I90kVPccPVc8AdOC00SfxtU7igGZ52iRNrjFzeR1ujYPBm", "username": null, "created_at": "2025-02-11 02:58:36", "updated_at": "2025-02-11 02:58:36", "remember_token": "xKFl4pEB1sGeZILezdQm2AHuYLmy6BmL5J1dBkfz8g8DeOm90fm7CL1pT29W", "email_verified_at": null}, "attributes": {"id": 7, "name": "Student", "email": "student@gmail.com", "photo": null, "password": "$2y$12$O/VLHJ/I90kVPccPVc8AdOC00SfxtU7igGZ52iRNrjFzeR1ujYPBm", "username": null, "created_at": "2025-02-11 02:58:36", "updated_at": "2025-02-11 02:58:36", "remember_token": "w4qSp9g01c9n93HfIcGbDfbZdO9XIHvdBqvwMlkpvFjFCRDADJ5K2ukYNsmX", "email_verified_at": null}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-02-11 03:59:35',
                'updated_at' => '2025-02-11 03:59:35',
            ),
            11 => 
            array (
                'id' => 12,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 7,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 7,
                'properties' => '{"old": {"id": 7, "name": "Student", "email": "student@gmail.com", "photo": null, "password": "$2y$12$O/VLHJ/I90kVPccPVc8AdOC00SfxtU7igGZ52iRNrjFzeR1ujYPBm", "username": null, "created_at": "2025-02-11 02:58:36", "updated_at": "2025-02-11 02:58:36", "remember_token": "w4qSp9g01c9n93HfIcGbDfbZdO9XIHvdBqvwMlkpvFjFCRDADJ5K2ukYNsmX", "email_verified_at": null}, "attributes": {"id": 7, "name": "Student", "email": "student@gmail.com", "photo": null, "password": "$2y$12$O/VLHJ/I90kVPccPVc8AdOC00SfxtU7igGZ52iRNrjFzeR1ujYPBm", "username": null, "created_at": "2025-02-11 02:58:36", "updated_at": "2025-02-11 02:58:36", "remember_token": "PF3ULgRFYcNtx9XANfqQuypRJ1PD3ojahlTbS2BvnYtoVMjvgqlVwXr7EP2D", "email_verified_at": null}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-02-11 04:02:12',
                'updated_at' => '2025-02-11 04:02:12',
            ),
            12 => 
            array (
                'id' => 13,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 7,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 7,
                'properties' => '{"old": {"id": 7, "name": "Student", "email": "student@gmail.com", "photo": null, "password": "$2y$12$O/VLHJ/I90kVPccPVc8AdOC00SfxtU7igGZ52iRNrjFzeR1ujYPBm", "username": null, "created_at": "2025-02-11 02:58:36", "updated_at": "2025-02-11 02:58:36", "remember_token": "PF3ULgRFYcNtx9XANfqQuypRJ1PD3ojahlTbS2BvnYtoVMjvgqlVwXr7EP2D", "email_verified_at": null}, "attributes": {"id": 7, "name": "Student", "email": "student@gmail.com", "photo": null, "password": "$2y$12$O/VLHJ/I90kVPccPVc8AdOC00SfxtU7igGZ52iRNrjFzeR1ujYPBm", "username": null, "created_at": "2025-02-11 02:58:36", "updated_at": "2025-02-11 02:58:36", "remember_token": "VylHnOCHWJrhnUyNCDkU51HVWhEHtnEC2cJtA6RTJE5zwAPBF7GlDLBt9bj3", "email_verified_at": null}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-03-25 19:47:42',
                'updated_at' => '2025-03-25 19:47:42',
            ),
            13 => 
            array (
                'id' => 14,
                'log_name' => 'default',
                'description' => 'created',
                'subject_type' => 'App\\Models\\Course',
                'event' => 'created',
                'subject_id' => 31,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 6,
                'properties' => '{"attributes": {"id": 31, "slug": "a", "goals": "a", "image": "images/AG63IeLDv0xYxxpHHtouVvOP75LSb6NSB4r5eNcJ.jpg", "level": "beginner", "price": -23356000, "title": "a", "status": 1, "duration": null, "created_at": "2025-03-25 20:37:31", "updated_at": "2025-03-25 20:37:31", "description": "a", "instructor_id": 6, "prerequisites": "a", "course_category_id": 4, "discount_percentage": 23456}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-03-25 20:37:31',
                'updated_at' => '2025-03-25 20:37:31',
            ),
            14 => 
            array (
                'id' => 15,
                'log_name' => 'default',
                'description' => 'created',
                'subject_type' => 'App\\Models\\Course',
                'event' => 'created',
                'subject_id' => 32,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 6,
                'properties' => '{"attributes": {"id": 32, "slug": "b", "goals": "b", "image": "images/puHixpB4n5Fr0qWKBiKpZCOW6YscigwL06o3RioY.jpg", "level": "beginner", "price": 80000, "title": "b", "status": 1, "duration": null, "created_at": "2025-03-25 20:40:06", "updated_at": "2025-03-25 20:40:06", "description": "b", "instructor_id": 6, "prerequisites": "b", "course_category_id": 1, "discount_percentage": 20}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-03-25 20:40:06',
                'updated_at' => '2025-03-25 20:40:06',
            ),
            15 => 
            array (
                'id' => 16,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\Course',
                'event' => 'updated',
                'subject_id' => 32,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 6,
                'properties' => '{"old": {"id": 32, "slug": "b", "goals": "b", "image": "images/puHixpB4n5Fr0qWKBiKpZCOW6YscigwL06o3RioY.jpg", "level": "beginner", "price": 80000, "title": "b", "status": 1, "duration": null, "created_at": "2025-03-25 20:40:06", "updated_at": "2025-03-25 20:40:06", "description": "b", "instructor_id": 6, "prerequisites": "b", "course_category_id": 1, "discount_percentage": 20}, "attributes": {"id": 32, "slug": "b", "goals": "b", "image": "images/puHixpB4n5Fr0qWKBiKpZCOW6YscigwL06o3RioY.jpg", "level": "beginner", "price": 80000, "title": "b", "status": 1, "duration": null, "created_at": "2025-03-25 20:40:06", "updated_at": "2025-03-25 20:43:38", "description": "b", "instructor_id": 6, "prerequisites": "b", "course_category_id": 1, "discount_percentage": 20}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-03-25 20:43:38',
                'updated_at' => '2025-03-25 20:43:38',
            ),
            16 => 
            array (
                'id' => 17,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\Course',
                'event' => 'updated',
                'subject_id' => 32,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 6,
                'properties' => '{"old": {"id": 32, "slug": "b", "goals": "b", "image": "images/puHixpB4n5Fr0qWKBiKpZCOW6YscigwL06o3RioY.jpg", "level": "beginner", "price": 80000, "title": "b", "status": 1, "duration": null, "created_at": "2025-03-25 20:40:06", "updated_at": "2025-03-25 20:43:38", "description": "b", "instructor_id": 6, "prerequisites": "b", "course_category_id": 1, "discount_percentage": 20}, "attributes": {"id": 32, "slug": "b", "goals": "b", "image": "images/puHixpB4n5Fr0qWKBiKpZCOW6YscigwL06o3RioY.jpg", "level": "beginner", "price": 80000, "title": "b", "status": 1, "duration": null, "created_at": "2025-03-25 20:40:06", "updated_at": "2025-03-25 20:45:01", "description": "b", "instructor_id": 6, "prerequisites": "b", "course_category_id": 1, "discount_percentage": 20}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-03-25 20:45:01',
                'updated_at' => '2025-03-25 20:45:01',
            ),
            17 => 
            array (
                'id' => 18,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\Course',
                'event' => 'updated',
                'subject_id' => 32,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 6,
                'properties' => '{"old": {"id": 32, "slug": "b", "goals": "b", "image": "images/puHixpB4n5Fr0qWKBiKpZCOW6YscigwL06o3RioY.jpg", "level": "beginner", "price": 80000, "title": "b", "status": 1, "duration": null, "created_at": "2025-03-25 20:40:06", "updated_at": "2025-03-25 20:45:01", "description": "b", "instructor_id": 6, "prerequisites": "b", "course_category_id": 1, "discount_percentage": 20}, "attributes": {"id": 32, "slug": "b", "goals": "b", "image": "images/puHixpB4n5Fr0qWKBiKpZCOW6YscigwL06o3RioY.jpg", "level": "beginner", "price": 48000, "title": "b", "status": 1, "duration": null, "created_at": "2025-03-25 20:40:06", "updated_at": "2025-03-25 20:50:01", "description": "b", "instructor_id": 6, "prerequisites": "b", "course_category_id": 1, "discount_percentage": 20}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-03-25 20:50:01',
                'updated_at' => '2025-03-25 20:50:01',
            ),
            18 => 
            array (
                'id' => 19,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\Course',
                'event' => 'updated',
                'subject_id' => 32,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 6,
                'properties' => '{"old": {"id": 32, "slug": "b", "goals": "b", "image": "images/puHixpB4n5Fr0qWKBiKpZCOW6YscigwL06o3RioY.jpg", "level": "beginner", "price": 48000, "title": "b", "status": 1, "duration": null, "created_at": "2025-03-25 20:40:06", "updated_at": "2025-03-25 20:50:01", "description": "b", "instructor_id": 6, "prerequisites": "b", "course_category_id": 1, "discount_percentage": 20}, "attributes": {"id": 32, "slug": "b", "goals": "b", "image": "images/puHixpB4n5Fr0qWKBiKpZCOW6YscigwL06o3RioY.jpg", "level": "beginner", "price": 48000, "title": "b", "status": 1, "duration": null, "created_at": "2025-03-25 20:40:06", "updated_at": "2025-03-25 20:50:31", "description": "b", "instructor_id": 6, "prerequisites": "b", "course_category_id": 1, "discount_percentage": 20}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-03-25 20:50:31',
                'updated_at' => '2025-03-25 20:50:31',
            ),
            19 => 
            array (
                'id' => 20,
                'log_name' => 'default',
                'description' => 'created',
                'subject_type' => 'App\\Models\\CourseSection',
                'event' => 'created',
                'subject_id' => 91,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 6,
                'properties' => '{"attributes": {"id": 91, "title": "Section 1", "course_id": 32, "created_at": "2025-03-25 21:09:20", "updated_at": "2025-03-25 21:09:20"}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-03-25 21:09:20',
                'updated_at' => '2025-03-25 21:09:20',
            ),
            20 => 
            array (
                'id' => 21,
                'log_name' => 'default',
                'description' => 'created',
                'subject_type' => 'App\\Models\\CourseLecture',
                'event' => 'created',
                'subject_id' => 271,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 6,
                'properties' => '{"attributes": {"id": 271, "title": "Lecture 1.1", "video": "videos/2be5RpzSqLwylV76RZs0f9XLki0shMv2xgY6iKK9.mp4", "course_id": 32, "created_at": "2025-03-25 21:18:41", "updated_at": "2025-03-25 21:18:41", "description": "Deksripsi Lecture 1.1", "set_as_preview": 0, "video_duration": 0, "set_as_featured": 0, "course_section_id": 91}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-03-25 21:18:41',
                'updated_at' => '2025-03-25 21:18:41',
            ),
            21 => 
            array (
                'id' => 22,
                'log_name' => 'default',
                'description' => 'deleted',
                'subject_type' => 'App\\Models\\CourseLecture',
                'event' => 'deleted',
                'subject_id' => 271,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 6,
                'properties' => '{"old": {"id": 271, "title": "Lecture 1.1", "video": "videos/2be5RpzSqLwylV76RZs0f9XLki0shMv2xgY6iKK9.mp4", "course_id": 32, "created_at": "2025-03-25 21:18:41", "updated_at": "2025-03-25 21:18:41", "description": "Deksripsi Lecture 1.1", "set_as_preview": 0, "video_duration": 0, "set_as_featured": 0, "course_section_id": 91}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-03-25 21:20:43',
                'updated_at' => '2025-03-25 21:20:43',
            ),
            22 => 
            array (
                'id' => 23,
                'log_name' => 'default',
                'description' => 'created',
                'subject_type' => 'App\\Models\\CourseLecture',
                'event' => 'created',
                'subject_id' => 272,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 6,
                'properties' => '{"attributes": {"id": 272, "title": "Lecture 1.1", "video": "videos/nEBA3ivRQ8QdHZyujCboB20NXZnrz0VUG69CcFLx.mp4", "course_id": 32, "created_at": "2025-03-25 21:21:07", "updated_at": "2025-03-25 21:21:07", "description": "Deskripsi Lecture 1.1", "set_as_preview": 0, "video_duration": 0, "set_as_featured": 1, "course_section_id": 91}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-03-25 21:21:07',
                'updated_at' => '2025-03-25 21:21:07',
            ),
            23 => 
            array (
                'id' => 24,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\CourseLecture',
                'event' => 'updated',
                'subject_id' => 272,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 6,
                'properties' => '{"old": {"id": 272, "title": "Lecture 1.1", "video": "videos/nEBA3ivRQ8QdHZyujCboB20NXZnrz0VUG69CcFLx.mp4", "course_id": 32, "created_at": "2025-03-25 21:21:07", "updated_at": "2025-03-25 21:21:07", "description": "Deskripsi Lecture 1.1", "set_as_preview": 0, "video_duration": 0, "set_as_featured": 1, "course_section_id": 91}, "attributes": {"id": 272, "title": "Lecture 1.1", "video": "videos/nEBA3ivRQ8QdHZyujCboB20NXZnrz0VUG69CcFLx.mp4", "course_id": 32, "created_at": "2025-03-25 21:21:07", "updated_at": "2025-03-25 21:29:23", "description": "Deskripsi Lecture 1.1", "set_as_preview": 1, "video_duration": 0, "set_as_featured": 1, "course_section_id": 91}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-03-25 21:29:23',
                'updated_at' => '2025-03-25 21:29:23',
            ),
            24 => 
            array (
                'id' => 25,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\CourseSection',
                'event' => 'updated',
                'subject_id' => 91,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 6,
                'properties' => '{"old": {"id": 91, "title": "Section 1", "course_id": 32, "created_at": "2025-03-25 21:09:20", "updated_at": "2025-03-25 21:09:20"}, "attributes": {"id": 91, "title": "Section 1 Update", "course_id": 32, "created_at": "2025-03-25 21:09:20", "updated_at": "2025-03-26 21:11:42"}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-03-26 21:11:43',
                'updated_at' => '2025-03-26 21:11:43',
            ),
            25 => 
            array (
                'id' => 26,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 7,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 7,
                'properties' => '{"old": {"id": 7, "name": "Student", "email": "student@gmail.com", "photo": null, "password": "$2y$12$O/VLHJ/I90kVPccPVc8AdOC00SfxtU7igGZ52iRNrjFzeR1ujYPBm", "username": null, "created_at": "2025-02-11 02:58:36", "updated_at": "2025-02-11 02:58:36", "remember_token": "VylHnOCHWJrhnUyNCDkU51HVWhEHtnEC2cJtA6RTJE5zwAPBF7GlDLBt9bj3", "email_verified_at": null}, "attributes": {"id": 7, "name": "Student", "email": "student@gmail.com", "photo": null, "password": "$2y$12$O/VLHJ/I90kVPccPVc8AdOC00SfxtU7igGZ52iRNrjFzeR1ujYPBm", "username": null, "created_at": "2025-02-11 02:58:36", "updated_at": "2025-02-11 02:58:36", "remember_token": "LD6xlKDYv8hoCxoORSTXHKR6yX0PpXPUdrqwXIE7iOHchxmmoATrW9KGU1UN", "email_verified_at": null}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-03-28 23:22:45',
                'updated_at' => '2025-03-28 23:22:45',
            ),
            26 => 
            array (
                'id' => 27,
                'log_name' => 'default',
                'description' => 'deleted',
                'subject_type' => 'App\\Models\\Course',
                'event' => 'deleted',
                'subject_id' => 32,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 5,
                'properties' => '{"old": {"id": 32, "slug": "b", "goals": "b", "image": "images/puHixpB4n5Fr0qWKBiKpZCOW6YscigwL06o3RioY.jpg", "level": "beginner", "price": 48000, "title": "b", "status": 1, "duration": null, "created_at": "2025-03-25 20:40:06", "updated_at": "2025-03-25 20:50:31", "description": "b", "instructor_id": 6, "prerequisites": "b", "course_category_id": 1, "discount_percentage": 20}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-04-12 02:28:04',
                'updated_at' => '2025-04-12 02:28:04',
            ),
            27 => 
            array (
                'id' => 28,
                'log_name' => 'default',
                'description' => 'deleted',
                'subject_type' => 'App\\Models\\Course',
                'event' => 'deleted',
                'subject_id' => 31,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 5,
                'properties' => '{"old": {"id": 31, "slug": "a", "goals": "a", "image": "images/AG63IeLDv0xYxxpHHtouVvOP75LSb6NSB4r5eNcJ.jpg", "level": "beginner", "price": -23356000, "title": "a", "status": 1, "duration": null, "created_at": "2025-03-25 20:37:31", "updated_at": "2025-03-25 20:37:31", "description": "a", "instructor_id": 6, "prerequisites": "a", "course_category_id": 4, "discount_percentage": 23456}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-04-12 02:28:07',
                'updated_at' => '2025-04-12 02:28:07',
            ),
            28 => 
            array (
                'id' => 29,
                'log_name' => 'default',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 10,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 5,
                'properties' => '{"attributes": {"id": 10, "name": "Vishwas", "email": "vishwas@gmail.com", "photo": null, "password": "$2y$12$JiQhPzZn2XgdJZukK71CXenXBzG1x53Bn9wxSuEhs.ex7vrgCTg9u", "username": null, "created_at": "2025-04-12 02:40:52", "updated_at": "2025-04-12 02:40:52", "remember_token": null, "email_verified_at": null}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-04-12 02:40:52',
                'updated_at' => '2025-04-12 02:40:52',
            ),
            29 => 
            array (
                'id' => 30,
                'log_name' => 'default',
                'description' => 'created',
                'subject_type' => 'App\\Models\\Course',
                'event' => 'created',
                'subject_id' => 33,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 5,
                'properties' => '{"attributes": {"id": 33, "slug": "reactjs-tutorial-for-beginners", "goals": "React has a component based architecture. This lets you break down your application into small encapsulated parts which can then be composed to make more complex UI.\\r\\nReact is declarative.\\r\\nReact will make it painless for you to create complex UIs by abstracting away the difficult parts. \\r\\nReact will handle efficiently updating and rendering just the right components in your application when your data changes. \\r\\nDOM updates which is one of the more expensive operations is handled gracefully in React.", "image": "images/arUQzEnCpt3BgoijRFYOmzXX6CLLT5PuebwVCGfF.png", "level": "beginner", "price": 120000, "title": "ReactJS Tutorial for Beginners", "status": 1, "duration": null, "created_at": "2025-04-12 02:50:10", "updated_at": "2025-04-12 02:50:10", "description": "React is an open source javascript library for building user interfaces.\\r\\nReact is a project created and maintained by Facebook.\\r\\nReact has more than a 100 thousand stars on GitHub and a huge community behind it.\\r\\nReact has become increasingly \\r\\npopular among developers and is also one of the most sought out skill-sets by companies right now.", "instructor_id": 10, "prerequisites": "HTML, CSS , Javascript", "course_category_id": 2, "discount_percentage": 0}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-04-12 02:50:10',
                'updated_at' => '2025-04-12 02:50:10',
            ),
            30 => 
            array (
                'id' => 31,
                'log_name' => 'default',
                'description' => 'created',
                'subject_type' => 'App\\Models\\CourseSection',
                'event' => 'created',
                'subject_id' => 92,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 5,
                'properties' => '{"attributes": {"id": 92, "title": "Introductions", "course_id": 33, "created_at": "2025-04-12 02:52:06", "updated_at": "2025-04-12 02:52:06"}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-04-12 02:52:06',
                'updated_at' => '2025-04-12 02:52:06',
            ),
            31 => 
            array (
                'id' => 32,
                'log_name' => 'default',
                'description' => 'created',
                'subject_type' => 'App\\Models\\CourseSection',
                'event' => 'created',
                'subject_id' => 93,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 5,
                'properties' => '{"attributes": {"id": 93, "title": "Basic Structure and Components", "course_id": 33, "created_at": "2025-04-12 02:52:46", "updated_at": "2025-04-12 02:52:46"}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-04-12 02:52:46',
                'updated_at' => '2025-04-12 02:52:46',
            ),
            32 => 
            array (
                'id' => 33,
                'log_name' => 'default',
                'description' => 'created',
                'subject_type' => 'App\\Models\\CourseLecture',
                'event' => 'created',
                'subject_id' => 273,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 5,
                'properties' => '{"attributes": {"id": 273, "title": "ReactJS Tutorial - 1 - Introduction", "video": "videos/7VKjkruxEROgsCfELmC1XjpqcN37urglrGBZyEEK.mp4", "course_id": 33, "created_at": "2025-04-12 04:34:57", "updated_at": "2025-04-12 04:34:57", "description": "React is an open source javascript library for building user interfaces.\\r\\nReact is a project created and maintained by Facebook.\\r\\nReact has more than a 100 thousand stars on GitHub and a huge community behind it.\\r\\nReact has become increasingly \\r\\npopular among developers and is also one of the most sought out skill-sets by companies right now.\\r\\n\\r\\nReact has a component based architecture. This lets you break down your application into small encapsulated parts which can then be composed to make more complex UI.\\r\\nReact is declarative.\\r\\nReact will make it painless for you to create complex UIs by abstracting away the difficult parts. \\r\\nReact will handle efficiently updating and rendering just the right components in your application when your data changes. \\r\\nDOM updates which is one of the more expensive operations is handled gracefully in React.", "set_as_preview": 0, "video_duration": 573.321, "set_as_featured": 0, "course_section_id": 92}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-04-12 04:34:57',
                'updated_at' => '2025-04-12 04:34:57',
            ),
            33 => 
            array (
                'id' => 34,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\CourseLecture',
                'event' => 'updated',
                'subject_id' => 273,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 5,
                'properties' => '{"old": {"id": 273, "title": "ReactJS Tutorial - 1 - Introduction", "video": "videos/7VKjkruxEROgsCfELmC1XjpqcN37urglrGBZyEEK.mp4", "course_id": 33, "created_at": "2025-04-12 04:34:57", "updated_at": "2025-04-12 04:34:57", "description": "React is an open source javascript library for building user interfaces.\\r\\nReact is a project created and maintained by Facebook.\\r\\nReact has more than a 100 thousand stars on GitHub and a huge community behind it.\\r\\nReact has become increasingly \\r\\npopular among developers and is also one of the most sought out skill-sets by companies right now.\\r\\n\\r\\nReact has a component based architecture. This lets you break down your application into small encapsulated parts which can then be composed to make more complex UI.\\r\\nReact is declarative.\\r\\nReact will make it painless for you to create complex UIs by abstracting away the difficult parts. \\r\\nReact will handle efficiently updating and rendering just the right components in your application when your data changes. \\r\\nDOM updates which is one of the more expensive operations is handled gracefully in React.", "set_as_preview": 0, "video_duration": 573.321, "set_as_featured": 0, "course_section_id": 92}, "attributes": {"id": 273, "title": "ReactJS Tutorial - 1 - Introduction", "video": "videos/7VKjkruxEROgsCfELmC1XjpqcN37urglrGBZyEEK.mp4", "course_id": 33, "created_at": "2025-04-12 04:34:57", "updated_at": "2025-04-12 04:49:24", "description": "React is an open source javascript library for building user interfaces.\\r\\nReact is a project created and maintained by Facebook.\\r\\nReact has more than a 100 thousand stars on GitHub and a huge community behind it.\\r\\nReact has become increasingly \\r\\npopular among developers and is also one of the most sought out skill-sets by companies right now.\\r\\n\\r\\nReact has a component based architecture. This lets you break down your application into small encapsulated parts which can then be composed to make more complex UI.\\r\\nReact is declarative.\\r\\nReact will make it painless for you to create complex UIs by abstracting away the difficult parts. \\r\\nReact will handle efficiently updating and rendering just the right components in your application when your data changes. \\r\\nDOM updates which is one of the more expensive operations is handled gracefully in React.", "set_as_preview": 1, "video_duration": 573.321, "set_as_featured": 0, "course_section_id": 92}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-04-12 04:49:24',
                'updated_at' => '2025-04-12 04:49:24',
            ),
            34 => 
            array (
                'id' => 35,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\CourseLecture',
                'event' => 'updated',
                'subject_id' => 273,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 5,
                'properties' => '{"old": {"id": 273, "title": "ReactJS Tutorial - 1 - Introduction", "video": "videos/7VKjkruxEROgsCfELmC1XjpqcN37urglrGBZyEEK.mp4", "course_id": 33, "created_at": "2025-04-12 04:34:57", "updated_at": "2025-04-12 04:49:24", "description": "React is an open source javascript library for building user interfaces.\\r\\nReact is a project created and maintained by Facebook.\\r\\nReact has more than a 100 thousand stars on GitHub and a huge community behind it.\\r\\nReact has become increasingly \\r\\npopular among developers and is also one of the most sought out skill-sets by companies right now.\\r\\n\\r\\nReact has a component based architecture. This lets you break down your application into small encapsulated parts which can then be composed to make more complex UI.\\r\\nReact is declarative.\\r\\nReact will make it painless for you to create complex UIs by abstracting away the difficult parts. \\r\\nReact will handle efficiently updating and rendering just the right components in your application when your data changes. \\r\\nDOM updates which is one of the more expensive operations is handled gracefully in React.", "set_as_preview": 1, "video_duration": 573.321, "set_as_featured": 0, "course_section_id": 92}, "attributes": {"id": 273, "title": "ReactJS Tutorial - 1 - Introduction", "video": "videos/7VKjkruxEROgsCfELmC1XjpqcN37urglrGBZyEEK.mp4", "course_id": 33, "created_at": "2025-04-12 04:34:57", "updated_at": "2025-04-12 04:49:26", "description": "React is an open source javascript library for building user interfaces.\\r\\nReact is a project created and maintained by Facebook.\\r\\nReact has more than a 100 thousand stars on GitHub and a huge community behind it.\\r\\nReact has become increasingly \\r\\npopular among developers and is also one of the most sought out skill-sets by companies right now.\\r\\n\\r\\nReact has a component based architecture. This lets you break down your application into small encapsulated parts which can then be composed to make more complex UI.\\r\\nReact is declarative.\\r\\nReact will make it painless for you to create complex UIs by abstracting away the difficult parts. \\r\\nReact will handle efficiently updating and rendering just the right components in your application when your data changes. \\r\\nDOM updates which is one of the more expensive operations is handled gracefully in React.", "set_as_preview": 1, "video_duration": 573.321, "set_as_featured": 1, "course_section_id": 92}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-04-12 04:49:26',
                'updated_at' => '2025-04-12 04:49:26',
            ),
            35 => 
            array (
                'id' => 36,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 7,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 7,
                'properties' => '{"old": {"id": 7, "name": "Student", "email": "student@gmail.com", "photo": null, "password": "$2y$12$O/VLHJ/I90kVPccPVc8AdOC00SfxtU7igGZ52iRNrjFzeR1ujYPBm", "username": null, "created_at": "2025-02-11 02:58:36", "updated_at": "2025-02-11 02:58:36", "remember_token": "LD6xlKDYv8hoCxoORSTXHKR6yX0PpXPUdrqwXIE7iOHchxmmoATrW9KGU1UN", "email_verified_at": null}, "attributes": {"id": 7, "name": "Student", "email": "student@gmail.com", "photo": null, "password": "$2y$12$O/VLHJ/I90kVPccPVc8AdOC00SfxtU7igGZ52iRNrjFzeR1ujYPBm", "username": null, "created_at": "2025-02-11 02:58:36", "updated_at": "2025-02-11 02:58:36", "remember_token": "CtzaabXdkRDxx1abZB0HazhbBCdUcWIb7F07DwX1w9gK9BEf29TpxdYm2ytG", "email_verified_at": null}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-04-12 05:31:49',
                'updated_at' => '2025-04-12 05:31:49',
            ),
            36 => 
            array (
                'id' => 37,
                'log_name' => 'default',
                'description' => 'created',
                'subject_type' => 'App\\Models\\CourseLecture',
                'event' => 'created',
                'subject_id' => 274,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 5,
                'properties' => '{"attributes": {"id": 274, "title": "ReactJS Tutorial - 2 - Hello World", "video": "videos/UpfXjHQ9Fp5jNPOjrrJhHPYqqUIVGsEWrkVGReXu.mp4", "course_id": 33, "created_at": "2025-04-12 07:27:38", "updated_at": "2025-04-12 07:27:38", "description": "Create React App is a comfortable environment for learning React, and is the best way to start building a new single-page application in React.\\r\\n\\r\\nIt sets up your development environment so that you can use the latest JavaScript features, provides a nice developer experience, and optimizes your app for production.", "set_as_preview": 0, "video_duration": 293.268027, "set_as_featured": 0, "course_section_id": 92}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-04-12 07:27:38',
                'updated_at' => '2025-04-12 07:27:38',
            ),
            37 => 
            array (
                'id' => 38,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\CourseLecture',
                'event' => 'updated',
                'subject_id' => 274,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 5,
                'properties' => '{"old": {"id": 274, "title": "ReactJS Tutorial - 2 - Hello World", "video": "videos/UpfXjHQ9Fp5jNPOjrrJhHPYqqUIVGsEWrkVGReXu.mp4", "course_id": 33, "created_at": "2025-04-12 07:27:38", "updated_at": "2025-04-12 07:27:38", "description": "Create React App is a comfortable environment for learning React, and is the best way to start building a new single-page application in React.\\r\\n\\r\\nIt sets up your development environment so that you can use the latest JavaScript features, provides a nice developer experience, and optimizes your app for production.", "set_as_preview": 0, "video_duration": 293.268027, "set_as_featured": 0, "course_section_id": 92}, "attributes": {"id": 274, "title": "ReactJS Tutorial - 2 - Hello World", "video": "videos/UpfXjHQ9Fp5jNPOjrrJhHPYqqUIVGsEWrkVGReXu.mp4", "course_id": 33, "created_at": "2025-04-12 07:27:38", "updated_at": "2025-04-12 07:27:46", "description": "Create React App is a comfortable environment for learning React, and is the best way to start building a new single-page application in React.\\r\\n\\r\\nIt sets up your development environment so that you can use the latest JavaScript features, provides a nice developer experience, and optimizes your app for production.", "set_as_preview": 1, "video_duration": 293.268027, "set_as_featured": 0, "course_section_id": 92}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-04-12 07:27:46',
                'updated_at' => '2025-04-12 07:27:46',
            ),
            38 => 
            array (
                'id' => 39,
                'log_name' => 'default',
                'description' => 'created',
                'subject_type' => 'App\\Models\\CourseLecture',
                'event' => 'created',
                'subject_id' => 275,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 5,
                'properties' => '{"attributes": {"id": 275, "title": "ReactJS Tutorial - 3 - Folder Structure", "video": "videos/6iggZWaZEaRHs6m7G6M8g06aOeFS9M7OSXgTUb0V.mp4", "course_id": 33, "created_at": "2025-04-12 07:28:48", "updated_at": "2025-04-12 07:28:48", "description": "Exploring the folder structure of a Create React App generated project.", "set_as_preview": 0, "video_duration": 334.808526, "set_as_featured": 0, "course_section_id": 93}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-04-12 07:28:48',
                'updated_at' => '2025-04-12 07:28:48',
            ),
            39 => 
            array (
                'id' => 40,
                'log_name' => 'default',
                'description' => 'created',
                'subject_type' => 'App\\Models\\CourseLecture',
                'event' => 'created',
                'subject_id' => 276,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 5,
            'properties' => '{"attributes": {"id": 276, "title": "ReactJS Tutorial - 4 - Components", "video": "videos/kdCpupk71LpE1XtCeERrJgKSEqkzlWJ6HMdnDAWL.mp4", "course_id": 33, "created_at": "2025-04-12 07:29:58", "updated_at": "2025-04-12 07:29:58", "description": "Components let you split the UI into independent, reusable pieces, and think about each piece in isolation.\\r\\nConceptually, components are like JavaScript functions. They accept arbitrary inputs (called “props”) and return React elements describing what should appear on the screen.\\r\\nThere are two types of components - Stateless Functional Components and Stateful Class Components", "set_as_preview": 0, "video_duration": 298.631837, "set_as_featured": 0, "course_section_id": 93}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-04-12 07:29:58',
                'updated_at' => '2025-04-12 07:29:58',
            ),
            40 => 
            array (
                'id' => 41,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\CourseLecture',
                'event' => 'updated',
                'subject_id' => 275,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 5,
                'properties' => '{"old": {"id": 275, "title": "ReactJS Tutorial - 3 - Folder Structure", "video": "videos/6iggZWaZEaRHs6m7G6M8g06aOeFS9M7OSXgTUb0V.mp4", "course_id": 33, "created_at": "2025-04-12 07:28:48", "updated_at": "2025-04-12 07:28:48", "description": "Exploring the folder structure of a Create React App generated project.", "set_as_preview": 0, "video_duration": 334.808526, "set_as_featured": 0, "course_section_id": 93}, "attributes": {"id": 275, "title": "ReactJS Tutorial - 3 - Folder Structure", "video": "videos/6iggZWaZEaRHs6m7G6M8g06aOeFS9M7OSXgTUb0V.mp4", "course_id": 33, "created_at": "2025-04-12 07:28:48", "updated_at": "2025-04-12 07:30:02", "description": "Exploring the folder structure of a Create React App generated project.", "set_as_preview": 1, "video_duration": 334.808526, "set_as_featured": 0, "course_section_id": 93}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-04-12 07:30:02',
                'updated_at' => '2025-04-12 07:30:02',
            ),
            41 => 
            array (
                'id' => 42,
                'log_name' => 'default',
                'description' => 'created',
                'subject_type' => 'App\\Models\\CourseLecture',
                'event' => 'created',
                'subject_id' => 277,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 5,
            'properties' => '{"attributes": {"id": 277, "title": "ReactJS Tutorial - 5 - Functional Components", "video": "videos/ATAiOqHNnNglRQMcMzroMnF8HHhLfWhSmtMRnVEb.mp4", "course_id": 33, "created_at": "2025-04-12 07:31:01", "updated_at": "2025-04-12 07:31:01", "description": "The simplest way to define a component is to write a JavaScript function. A valid React component because it accepts a single “props” (which stands for properties) object argument with data and returns a React element. We call such components “function components” because they are literally JavaScript functions.", "set_as_preview": 0, "video_duration": 392.672653, "set_as_featured": 0, "course_section_id": 93}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-04-12 07:31:01',
                'updated_at' => '2025-04-12 07:31:01',
            ),
            42 => 
            array (
                'id' => 43,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\CourseLecture',
                'event' => 'updated',
                'subject_id' => 274,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 5,
                'properties' => '{"old": {"id": 274, "title": "ReactJS Tutorial - 2 - Hello World", "video": "videos/UpfXjHQ9Fp5jNPOjrrJhHPYqqUIVGsEWrkVGReXu.mp4", "course_id": 33, "created_at": "2025-04-12 07:27:38", "updated_at": "2025-04-12 07:27:46", "description": "Create React App is a comfortable environment for learning React, and is the best way to start building a new single-page application in React.\\r\\n\\r\\nIt sets up your development environment so that you can use the latest JavaScript features, provides a nice developer experience, and optimizes your app for production.", "set_as_preview": 1, "video_duration": 293.268027, "set_as_featured": 0, "course_section_id": 92}, "attributes": {"id": 274, "title": "ReactJS Tutorial - 2 - Hello World", "video": "videos/UpfXjHQ9Fp5jNPOjrrJhHPYqqUIVGsEWrkVGReXu.mp4", "course_id": 33, "created_at": "2025-04-12 07:27:38", "updated_at": "2025-04-12 07:31:44", "description": "Create React App is a comfortable environment for learning React, and is the best way to start building a new single-page application in React.\\r\\n\\r\\nIt sets up your development environment so that you can use the latest JavaScript features, provides a nice developer experience, and optimizes your app for production.", "set_as_preview": 0, "video_duration": 293.268027, "set_as_featured": 0, "course_section_id": 92}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-04-12 07:31:44',
                'updated_at' => '2025-04-12 07:31:44',
            ),
            43 => 
            array (
                'id' => 44,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\CourseLecture',
                'event' => 'updated',
                'subject_id' => 275,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 5,
                'properties' => '{"old": {"id": 275, "title": "ReactJS Tutorial - 3 - Folder Structure", "video": "videos/6iggZWaZEaRHs6m7G6M8g06aOeFS9M7OSXgTUb0V.mp4", "course_id": 33, "created_at": "2025-04-12 07:28:48", "updated_at": "2025-04-12 07:30:02", "description": "Exploring the folder structure of a Create React App generated project.", "set_as_preview": 1, "video_duration": 334.808526, "set_as_featured": 0, "course_section_id": 93}, "attributes": {"id": 275, "title": "ReactJS Tutorial - 3 - Folder Structure", "video": "videos/6iggZWaZEaRHs6m7G6M8g06aOeFS9M7OSXgTUb0V.mp4", "course_id": 33, "created_at": "2025-04-12 07:28:48", "updated_at": "2025-04-12 07:31:45", "description": "Exploring the folder structure of a Create React App generated project.", "set_as_preview": 0, "video_duration": 334.808526, "set_as_featured": 0, "course_section_id": 93}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-04-12 07:31:45',
                'updated_at' => '2025-04-12 07:31:45',
            ),
            44 => 
            array (
                'id' => 45,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\CourseLecture',
                'event' => 'updated',
                'subject_id' => 274,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 5,
                'properties' => '{"old": {"id": 274, "title": "ReactJS Tutorial - 2 - Hello World", "video": "videos/UpfXjHQ9Fp5jNPOjrrJhHPYqqUIVGsEWrkVGReXu.mp4", "course_id": 33, "created_at": "2025-04-12 07:27:38", "updated_at": "2025-04-12 07:31:44", "description": "Create React App is a comfortable environment for learning React, and is the best way to start building a new single-page application in React.\\r\\n\\r\\nIt sets up your development environment so that you can use the latest JavaScript features, provides a nice developer experience, and optimizes your app for production.", "set_as_preview": 0, "video_duration": 293.268027, "set_as_featured": 0, "course_section_id": 92}, "attributes": {"id": 274, "title": "ReactJS Tutorial - 2 - Hello World", "video": "videos/UpfXjHQ9Fp5jNPOjrrJhHPYqqUIVGsEWrkVGReXu.mp4", "course_id": 33, "created_at": "2025-04-12 07:27:38", "updated_at": "2025-04-12 07:32:04", "description": "Create React App is a comfortable environment for learning React, and is the best way to start building a new single-page application in React.\\r\\n\\r\\nIt sets up your development environment so that you can use the latest JavaScript features, provides a nice developer experience, and optimizes your app for production.", "set_as_preview": 1, "video_duration": 293.268027, "set_as_featured": 0, "course_section_id": 92}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-04-12 07:32:04',
                'updated_at' => '2025-04-12 07:32:04',
            ),
            45 => 
            array (
                'id' => 46,
                'log_name' => 'default',
                'description' => 'updated',
                'subject_type' => 'App\\Models\\User',
                'event' => 'updated',
                'subject_id' => 7,
                'causer_type' => 'App\\Models\\User',
                'causer_id' => 7,
                'properties' => '{"old": {"id": 7, "bio": null, "name": "Student", "email": "student@gmail.com", "photo": null, "password": "$2y$12$O/VLHJ/I90kVPccPVc8AdOC00SfxtU7igGZ52iRNrjFzeR1ujYPBm", "username": null, "created_at": "2025-02-11 02:58:36", "updated_at": "2025-02-11 02:58:36", "remember_token": "CtzaabXdkRDxx1abZB0HazhbBCdUcWIb7F07DwX1w9gK9BEf29TpxdYm2ytG", "email_verified_at": null}, "attributes": {"id": 7, "bio": null, "name": "Student", "email": "student@gmail.com", "photo": null, "password": "$2y$12$O/VLHJ/I90kVPccPVc8AdOC00SfxtU7igGZ52iRNrjFzeR1ujYPBm", "username": null, "created_at": "2025-02-11 02:58:36", "updated_at": "2025-02-11 02:58:36", "remember_token": "cL8Vd45ibiYyilhrhSbsppofRIYREqgp2bVDXGhtie4HcXAHe0oD3YuSiEZ0", "email_verified_at": null}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-04-14 03:25:09',
                'updated_at' => '2025-04-14 03:25:09',
            ),
            46 => 
            array (
                'id' => 47,
                'log_name' => 'default',
                'description' => 'created',
                'subject_type' => 'App\\Models\\User',
                'event' => 'created',
                'subject_id' => 11,
                'causer_type' => NULL,
                'causer_id' => NULL,
                'properties' => '{"attributes": {"id": 11, "bio": null, "name": "Fakhrurrazi", "email": "fakhrurrazi.code@gmail.com", "photo": "avatars/qfkDFjj7QP.png", "password": "$2y$12$4tF.dUofG6aHhgJVSBc50O6CsYnl7U4Q995smlQsPOXPpNGt42TgG", "username": "fakhrurrazi.code", "created_at": "2025-04-14 07:45:50", "updated_at": "2025-04-14 07:45:50", "remember_token": null, "email_verified_at": null}}',
                'batch_uuid' => NULL,
                'created_at' => '2025-04-14 07:45:50',
                'updated_at' => '2025-04-14 07:45:50',
            ),
        ));
        
        
    }
}