<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CoursesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('courses')->delete();
        
        \DB::table('courses')->insert(array (
            0 => 
            array (
                'id' => 30,
                'course_category_id' => 15,
                'instructor_id' => 8,
                'image' => NULL,
                'title' => 'Pengujian Keamanan Aplikasi Web',
                'slug' => 'pengujian-keamanan-aplikasi-web',
                'description' => 'Belajar metode pengujian keamanan pada aplikasi web.',
                'prerequisites' => 'Pemahaman dasar keamanan siber.',
                'goals' => 'Mampu melakukan penetration testing terhadap aplikasi web.',
                'duration' => 210,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 28,
                'course_category_id' => 14,
                'instructor_id' => 9,
                'image' => NULL,
                'title' => 'Optimasi Query dan Indexing di MySQL',
                'slug' => 'optimasi-query-indexing-mysql',
                'description' => 'Pelajari cara meningkatkan performa database dengan query dan indexing yang efisien.',
                'prerequisites' => 'Pemahaman dasar SQL.',
                'goals' => 'Mampu mengoptimalkan database untuk performa tinggi.',
                'duration' => 200,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 29,
                'course_category_id' => 15,
                'instructor_id' => 9,
                'image' => NULL,
                'title' => 'Software Testing & QA Automation',
                'slug' => 'software-testing-qa-automation',
                'description' => 'Pelajari teknik pengujian perangkat lunak dan otomatisasi QA.',
                'prerequisites' => 'Pemahaman dasar pemrograman.',
                'goals' => 'Mampu melakukan pengujian perangkat lunak dengan teknik manual dan otomatis.',
                'duration' => 190,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 25,
                'course_category_id' => 13,
                'instructor_id' => 9,
                'image' => NULL,
                'title' => 'Pemrograman Game dengan Unity dan C#',
                'slug' => 'pemrograman-game-unity-csharp',
                'description' => 'Belajar membuat game dengan Unity dan bahasa pemrograman C#.',
                'prerequisites' => 'Dasar pemrograman.',
                'goals' => 'Mampu membangun game sederhana menggunakan Unity.',
                'duration' => 240,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 26,
                'course_category_id' => 13,
                'instructor_id' => 9,
                'image' => NULL,
                'title' => 'Game Development dengan Unreal Engine',
                'slug' => 'game-development-unreal-engine',
                'description' => 'Pelajari pengembangan game menggunakan Unreal Engine.',
                'prerequisites' => 'Pemahaman dasar pemrograman.',
                'goals' => 'Mampu membuat game berbasis Unreal Engine.',
                'duration' => 260,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 27,
                'course_category_id' => 14,
                'instructor_id' => 9,
                'image' => NULL,
                'title' => 'Manajemen Basis Data dengan PostgreSQL',
                'slug' => 'manajemen-basis-data-postgresql',
                'description' => 'Belajar konsep manajemen basis data dengan PostgreSQL.',
                'prerequisites' => 'Dasar SQL.',
                'goals' => 'Mampu mengelola database menggunakan PostgreSQL.',
                'duration' => 180,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 22,
                'course_category_id' => 11,
                'instructor_id' => 8,
                'image' => NULL,
                'title' => 'Desain Sistem UI/UX untuk Aplikasi Web',
                'slug' => 'desain-sistem-uiux-aplikasi-web',
                'description' => 'Pelajari cara mendesain UI/UX untuk aplikasi web secara profesional.',
                'prerequisites' => 'Pemahaman dasar desain.',
                'goals' => 'Mampu membuat desain UI/UX berbasis pengalaman pengguna.',
                'duration' => 200,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 23,
                'course_category_id' => 12,
                'instructor_id' => 6,
                'image' => NULL,
            'title' => 'Internet of Things (IoT) dengan Arduino',
                'slug' => 'iot-arduino',
                'description' => 'Pelajari cara membuat perangkat IoT menggunakan Arduino.',
                'prerequisites' => 'Dasar pemrograman.',
                'goals' => 'Mampu membangun proyek IoT sederhana dengan Arduino.',
                'duration' => 200,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 24,
                'course_category_id' => 12,
                'instructor_id' => 6,
                'image' => NULL,
                'title' => 'Membangun Sistem IoT dengan Raspberry Pi',
                'slug' => 'membangun-iot-raspberry-pi',
                'description' => 'Pelajari cara membuat sistem berbasis IoT menggunakan Raspberry Pi.',
                'prerequisites' => 'Dasar pemrograman Python.',
                'goals' => 'Mampu menghubungkan perangkat IoT dengan cloud.',
                'duration' => 220,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 19,
                'course_category_id' => 10,
                'instructor_id' => 6,
                'image' => NULL,
                'title' => 'Blockchain dan Cryptocurrency: Dasar hingga Lanjutan',
                'slug' => 'blockchain-cryptocurrency',
                'description' => 'Pelajari dasar-dasar blockchain dan implementasi cryptocurrency.',
                'prerequisites' => 'Tidak ada, cocok untuk pemula.',
                'goals' => 'Memahami cara kerja blockchain dan mata uang kripto.',
                'duration' => 200,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 20,
                'course_category_id' => 10,
                'instructor_id' => 6,
                'image' => NULL,
                'title' => 'Smart Contract Development dengan Ethereum',
                'slug' => 'smart-contract-ethereum',
                'description' => 'Belajar membangun smart contract di blockchain Ethereum.',
                'prerequisites' => 'Dasar pemrograman.',
                'goals' => 'Mampu membuat smart contract menggunakan Solidity.',
                'duration' => 220,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 21,
                'course_category_id' => 11,
                'instructor_id' => 6,
                'image' => NULL,
                'title' => 'UI/UX Design dengan Figma dan Adobe XD',
                'slug' => 'ui-ux-design-figma-xd',
                'description' => 'Pelajari konsep desain UI/UX dan cara membuat prototipe dengan Figma dan Adobe XD.',
                'prerequisites' => 'Tidak ada, cocok untuk pemula.',
                'goals' => 'Mampu merancang antarmuka pengguna yang menarik dan fungsional.',
                'duration' => 180,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 17,
                'course_category_id' => 9,
                'instructor_id' => 6,
                'image' => NULL,
                'title' => 'Membangun Chatbot dengan Dialogflow dan Node.js',
                'slug' => 'membangun-chatbot-dialogflow',
                'description' => 'Pelajari cara membuat chatbot menggunakan Dialogflow dan Node.js.',
                'prerequisites' => 'Dasar JavaScript.',
                'goals' => 'Mampu membangun chatbot interaktif untuk berbagai keperluan.',
                'duration' => 160,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 18,
                'course_category_id' => 9,
                'instructor_id' => 9,
                'image' => NULL,
                'title' => 'Membangun AI Voice Assistant',
                'slug' => 'membangun-ai-voice-assistant',
                'description' => 'Pelajari cara membuat voice assistant berbasis AI.',
                'prerequisites' => 'Dasar pemrograman Python.',
                'goals' => 'Mampu membangun asisten suara berbasis AI.',
                'duration' => 180,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 14,
                'course_category_id' => 7,
                'instructor_id' => 6,
                'image' => NULL,
                'title' => 'Networking Fundamentals dengan Cisco',
                'slug' => 'networking-fundamentals-cisco',
                'description' => 'Pelajari dasar-dasar jaringan komputer dengan teknologi Cisco.',
                'prerequisites' => 'Tidak ada, cocok untuk pemula.',
                'goals' => 'Memahami dasar konfigurasi jaringan menggunakan perangkat Cisco.',
                'duration' => 180,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 15,
                'course_category_id' => 8,
                'instructor_id' => 8,
                'image' => NULL,
                'title' => 'DevOps dengan Docker dan Kubernetes',
                'slug' => 'devops-docker-kubernetes',
                'description' => 'Belajar konsep DevOps dan cara mengelola aplikasi dengan Docker dan Kubernetes.',
                'prerequisites' => 'Dasar pemrograman dan Linux.',
                'goals' => 'Mampu menggunakan Docker dan Kubernetes dalam proses deployment.',
                'duration' => 200,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 16,
                'course_category_id' => 8,
                'instructor_id' => 6,
                'image' => NULL,
                'title' => 'Cloud Computing dengan AWS',
                'slug' => 'cloud-computing-aws',
                'description' => 'Pelajari cara menggunakan layanan AWS untuk kebutuhan cloud computing.',
                'prerequisites' => 'Dasar jaringan dan sistem operasi.',
                'goals' => 'Mampu menggunakan AWS untuk hosting dan pengelolaan aplikasi.',
                'duration' => 220,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 11,
                'course_category_id' => 6,
                'instructor_id' => 6,
                'image' => NULL,
                'title' => 'Pengembangan Aplikasi Mobile dengan React Native',
                'slug' => 'pengembangan-aplikasi-react-native',
                'description' => 'Belajar membuat aplikasi mobile lintas platform dengan React Native.',
                'prerequisites' => 'Pemahaman dasar JavaScript dan React.',
                'goals' => 'Mampu membangun aplikasi mobile sederhana dengan React Native.',
                'duration' => 180,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 12,
                'course_category_id' => 6,
                'instructor_id' => 6,
                'image' => NULL,
                'title' => 'Pemrograman Kotlin untuk Android',
                'slug' => 'pemrograman-kotlin-android',
                'description' => 'Pelajari cara membangun aplikasi Android menggunakan Kotlin.',
                'prerequisites' => 'Dasar pemrograman.',
                'goals' => 'Mampu membuat aplikasi Android dengan Kotlin.',
                'duration' => 200,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 13,
                'course_category_id' => 7,
                'instructor_id' => 8,
                'image' => NULL,
                'title' => 'Dasar-Dasar Jaringan Komputer dan Keamanan',
                'slug' => 'dasar-jaringan-komputer-keamanan',
                'description' => 'Pelajari konsep dasar jaringan komputer dan keamanan siber.',
                'prerequisites' => 'Tidak ada, cocok untuk pemula.',
                'goals' => 'Memahami konsep dasar jaringan dan keamanan.',
                'duration' => 160,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 9,
                'course_category_id' => 5,
                'instructor_id' => 8,
                'image' => NULL,
                'title' => 'Ethical Hacking dan Penetration Testing',
                'slug' => 'ethical-hacking-penetration-testing',
                'description' => 'Belajar teknik ethical hacking dan cara melakukan penetration testing.',
                'prerequisites' => 'Dasar-dasar jaringan dan sistem operasi Linux.',
                'goals' => 'Memahami cara mengamankan sistem dari serangan siber.',
                'duration' => 240,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 10,
                'course_category_id' => 5,
                'instructor_id' => 8,
                'image' => NULL,
                'title' => 'Cybersecurity for Business',
                'slug' => 'cybersecurity-for-business',
                'description' => 'Pelajari konsep keamanan siber untuk perlindungan bisnis.',
                'prerequisites' => 'Tidak ada, cocok untuk pemula.',
                'goals' => 'Mampu memahami ancaman keamanan digital dan mitigasinya.',
                'duration' => 180,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 6,
                'course_category_id' => 3,
                'instructor_id' => 9,
                'image' => NULL,
                'title' => 'Data Science dengan Pandas dan NumPy',
                'slug' => 'data-science-pandas-numpy',
                'description' => 'Pelajari teknik manipulasi data menggunakan Pandas dan NumPy.',
                'prerequisites' => 'Dasar pemrograman Python.',
                'goals' => 'Mampu mengolah dan menganalisis data dengan Python.',
                'duration' => 180,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 7,
                'course_category_id' => 4,
                'instructor_id' => 9,
                'image' => NULL,
                'title' => 'Membangun API dengan Express.js dan MongoDB',
                'slug' => 'api-express-mongodb',
                'description' => 'Panduan lengkap dalam membuat RESTful API dengan Express.js dan MongoDB.',
                'prerequisites' => 'Pemahaman dasar JavaScript dan Node.js.',
                'goals' => 'Mampu membangun backend API dengan Express.js dan database MongoDB.',
                'duration' => 150,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 8,
                'course_category_id' => 4,
                'instructor_id' => 6,
                'image' => NULL,
                'title' => 'Membangun Microservices dengan Spring Boot',
                'slug' => 'microservices-spring-boot',
                'description' => 'Belajar konsep microservices dan implementasinya menggunakan Spring Boot.',
                'prerequisites' => 'Dasar pemrograman Java.',
                'goals' => 'Mampu membangun aplikasi berbasis microservices.',
                'duration' => 200,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 4,
                'course_category_id' => 2,
                'instructor_id' => 6,
                'image' => NULL,
                'title' => 'Membangun Website dengan HTML, CSS, dan JavaScript',
                'slug' => 'membangun-website-html-css-js',
                'description' => 'Pelajari cara membuat website dari nol menggunakan HTML, CSS, dan JavaScript.',
                'prerequisites' => 'Tidak ada, cocok untuk pemula.',
                'goals' => 'Mampu membangun halaman web statis yang menarik.',
                'duration' => 120,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 5,
                'course_category_id' => 3,
                'instructor_id' => 9,
                'image' => NULL,
                'title' => 'Machine Learning untuk Pemula dengan Python',
                'slug' => 'machine-learning-pemula-python',
                'description' => 'Pengenalan dasar machine learning dengan Python dan pustaka scikit-learn.',
                'prerequisites' => 'Pemrograman dasar Python.',
                'goals' => 'Mampu memahami konsep machine learning dan menerapkan algoritma sederhana.',
                'duration' => 200,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            27 => 
            array (
                'id' => 1,
                'course_category_id' => 1,
                'instructor_id' => 8,
                'image' => NULL,
                'title' => 'Dasar-Dasar Pemrograman dengan Python',
                'slug' => 'dasar-pemrograman-python',
                'description' => 'Pelajari konsep dasar pemrograman menggunakan Python dari nol.',
                'prerequisites' => 'Tidak ada, cocok untuk pemula.',
                'goals' => 'Memahami sintaks dasar Python dan mampu membuat program sederhana.',
                'duration' => 120,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            28 => 
            array (
                'id' => 2,
                'course_category_id' => 1,
                'instructor_id' => 8,
                'image' => NULL,
                'title' => 'Algoritma dan Struktur Data dengan Python',
                'slug' => 'algoritma-struktur-data-python',
                'description' => 'Pelajari konsep dasar algoritma dan struktur data dengan Python.',
                'prerequisites' => 'Dasar pemrograman Python.',
                'goals' => 'Mampu mengimplementasikan algoritma dan struktur data dalam Python.',
                'duration' => 150,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            29 => 
            array (
                'id' => 3,
                'course_category_id' => 2,
                'instructor_id' => 6,
                'image' => NULL,
                'title' => 'Full-Stack Web Development dengan Next.js dan MySQL',
                'slug' => 'fullstack-web-nextjs-mysql',
                'description' => 'Belajar membangun aplikasi web full-stack dengan Next.js dan MySQL.',
                'prerequisites' => 'Pemahaman dasar HTML, CSS, dan JavaScript.',
                'goals' => 'Mampu membangun aplikasi web dengan Next.js dan menghubungkannya dengan MySQL.',
                'duration' => 180,
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}