<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CoursesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('courses')->delete();
        
        \DB::table('courses')->insert(array (
            0 => 
            array (
                'id' => 7,
                'course_category_id' => 4,
                'instructor_id' => 9,
                'image' => 'images/4yGKoZrIZdgKkXgX7Ss0Iq717ethZMB4HhiKS7YD.jpg',
                'title' => 'Membangun API dengan Express.js dan MongoDB',
                'slug' => 'api-express-mongodb',
                'description' => 'Panduan lengkap dalam membuat RESTful API dengan Express.js dan MongoDB.',
                'prerequisites' => 'Pemahaman dasar JavaScript dan Node.js.',
                'goals' => 'Mampu membangun backend API dengan Express.js dan database MongoDB.',
                'duration' => 150,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:51:13',
                'discount_percentage' => 5.0,
            ),
            1 => 
            array (
                'id' => 6,
                'course_category_id' => 3,
                'instructor_id' => 9,
                'image' => 'images/ZcQpujsXvC5mTr63vi2qd7Zz2hji7S88ZVAUJToR.jpg',
                'title' => 'Data Science dengan Pandas dan NumPy',
                'slug' => 'data-science-pandas-numpy',
                'description' => 'Pelajari teknik manipulasi data menggunakan Pandas dan NumPy.',
                'prerequisites' => 'Dasar pemrograman Python.',
                'goals' => 'Mampu mengolah dan menganalisis data dengan Python.',
                'duration' => 180,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:49:58',
                'discount_percentage' => 5.0,
            ),
            2 => 
            array (
                'id' => 10,
                'course_category_id' => 5,
                'instructor_id' => 8,
                'image' => 'images/Oocgu99p1cxyBfiPLW5U4K1ncUmgIpkukNTxY9kB.jpg',
                'title' => 'Cybersecurity for Business',
                'slug' => 'cybersecurity-for-business',
                'description' => 'Pelajari konsep keamanan siber untuk perlindungan bisnis.',
                'prerequisites' => 'Tidak ada, cocok untuk pemula.',
                'goals' => 'Mampu memahami ancaman keamanan digital dan mitigasinya.',
                'duration' => 180,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:40:41',
                'discount_percentage' => 5.0,
            ),
            3 => 
            array (
                'id' => 9,
                'course_category_id' => 5,
                'instructor_id' => 8,
                'image' => 'images/4oI7ekMBgvkikcAFP0BnsLl66puSWjtGllN9s1jK.jpg',
                'title' => 'Ethical Hacking dan Penetration Testing',
                'slug' => 'ethical-hacking-penetration-testing',
                'description' => 'Belajar teknik ethical hacking dan cara melakukan penetration testing.',
                'prerequisites' => 'Dasar-dasar jaringan dan sistem operasi Linux.',
                'goals' => 'Memahami cara mengamankan sistem dari serangan siber.',
                'duration' => 240,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:39:21',
                'discount_percentage' => 5.0,
            ),
            4 => 
            array (
                'id' => 13,
                'course_category_id' => 7,
                'instructor_id' => 8,
                'image' => 'images/Aycfq3w9AnAH4K0zzzIsOH5CFYpylGhnAiXt5HVh.jpg',
                'title' => 'Dasar-Dasar Jaringan Komputer dan Keamanan',
                'slug' => 'dasar-jaringan-komputer-keamanan',
                'description' => 'Pelajari konsep dasar jaringan komputer dan keamanan siber.',
                'prerequisites' => 'Tidak ada, cocok untuk pemula.',
                'goals' => 'Memahami konsep dasar jaringan dan keamanan.',
                'duration' => 160,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:38:18',
                'discount_percentage' => 5.0,
            ),
            5 => 
            array (
                'id' => 12,
                'course_category_id' => 6,
                'instructor_id' => 6,
                'image' => 'images/ZZdIpZZi2PIrEj0Zrb0jZLGEpTIMUBn58WJcOpVQ.jpg',
                'title' => 'Pemrograman Kotlin untuk Android',
                'slug' => 'pemrograman-kotlin-android',
                'description' => 'Pelajari cara membangun aplikasi Android menggunakan Kotlin.',
                'prerequisites' => 'Dasar pemrograman.',
                'goals' => 'Mampu membuat aplikasi Android dengan Kotlin.',
                'duration' => 200,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:22:33',
                'discount_percentage' => 5.0,
            ),
            6 => 
            array (
                'id' => 11,
                'course_category_id' => 6,
                'instructor_id' => 6,
                'image' => 'images/18e2ym2egJzPQUiKFkTQ8fxZoClaCOPBrsRrT2dy.jpg',
                'title' => 'Pengembangan Aplikasi Mobile dengan React Native',
                'slug' => 'pengembangan-aplikasi-react-native',
                'description' => 'Belajar membuat aplikasi mobile lintas platform dengan React Native.',
                'prerequisites' => 'Pemahaman dasar JavaScript dan React.',
                'goals' => 'Mampu membangun aplikasi mobile sederhana dengan React Native.',
                'duration' => 180,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:21:26',
                'discount_percentage' => 5.0,
            ),
            7 => 
            array (
                'id' => 16,
                'course_category_id' => 8,
                'instructor_id' => 6,
                'image' => 'images/IOBJgjZEsHZV7U9CrpSQdRtV1bwzSmEeGuC5pjZ3.jpg',
                'title' => 'Cloud Computing dengan AWS',
                'slug' => 'cloud-computing-aws',
                'description' => 'Pelajari cara menggunakan layanan AWS untuk kebutuhan cloud computing.',
                'prerequisites' => 'Dasar jaringan dan sistem operasi.',
                'goals' => 'Mampu menggunakan AWS untuk hosting dan pengelolaan aplikasi.',
                'duration' => 220,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:19:11',
                'discount_percentage' => 5.0,
            ),
            8 => 
            array (
                'id' => 15,
                'course_category_id' => 8,
                'instructor_id' => 8,
                'image' => 'images/5dK2o8uOMfXjfxulpymOFjguW90WSOGL22uvmH45.jpg',
                'title' => 'DevOps dengan Docker dan Kubernetes',
                'slug' => 'devops-docker-kubernetes',
                'description' => 'Belajar konsep DevOps dan cara mengelola aplikasi dengan Docker dan Kubernetes.',
                'prerequisites' => 'Dasar pemrograman dan Linux.',
                'goals' => 'Mampu menggunakan Docker dan Kubernetes dalam proses deployment.',
                'duration' => 200,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:37:24',
                'discount_percentage' => 5.0,
            ),
            9 => 
            array (
                'id' => 14,
                'course_category_id' => 7,
                'instructor_id' => 6,
                'image' => 'images/w1zz43prxpf8fSoL4MIu5SyCUi0lwMYV6uHEDPJc.jpg',
                'title' => 'Networking Fundamentals dengan Cisco',
                'slug' => 'networking-fundamentals-cisco',
                'description' => 'Pelajari dasar-dasar jaringan komputer dengan teknologi Cisco.',
                'prerequisites' => 'Tidak ada, cocok untuk pemula.',
                'goals' => 'Memahami dasar konfigurasi jaringan menggunakan perangkat Cisco.',
                'duration' => 180,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:17:49',
                'discount_percentage' => 5.0,
            ),
            10 => 
            array (
                'id' => 18,
                'course_category_id' => 9,
                'instructor_id' => 9,
                'image' => 'images/WHT6Rv0FdBLx72K1as9jKd10bu2KBeb438wkrbkB.jpg',
                'title' => 'Membangun AI Voice Assistant',
                'slug' => 'membangun-ai-voice-assistant',
                'description' => 'Pelajari cara membuat voice assistant berbasis AI.',
                'prerequisites' => 'Dasar pemrograman Python.',
                'goals' => 'Mampu membangun asisten suara berbasis AI.',
                'duration' => 180,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:48:53',
                'discount_percentage' => NULL,
            ),
            11 => 
            array (
                'id' => 17,
                'course_category_id' => 9,
                'instructor_id' => 6,
                'image' => 'images/6qt1bmLqLNNhdgbrnWGT2PYo789DTGb49XcQ017M.jpg',
                'title' => 'Membangun Chatbot dengan Dialogflow dan Node.js',
                'slug' => 'membangun-chatbot-dialogflow',
                'description' => 'Pelajari cara membuat chatbot menggunakan Dialogflow dan Node.js.',
                'prerequisites' => 'Dasar JavaScript.',
                'goals' => 'Mampu membangun chatbot interaktif untuk berbagai keperluan.',
                'duration' => 160,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:16:06',
                'discount_percentage' => NULL,
            ),
            12 => 
            array (
                'id' => 21,
                'course_category_id' => 11,
                'instructor_id' => 6,
                'image' => 'images/Ce0sELSTX6sSZ4dEuCygz8IzBn2JU6TqXBilgYZx.jpg',
                'title' => 'UI/UX Design dengan Figma dan Adobe XD',
                'slug' => 'ui-ux-design-figma-xd',
                'description' => 'Pelajari konsep desain UI/UX dan cara membuat prototipe dengan Figma dan Adobe XD.',
                'prerequisites' => 'Tidak ada, cocok untuk pemula.',
                'goals' => 'Mampu merancang antarmuka pengguna yang menarik dan fungsional.',
                'duration' => 180,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:14:53',
                'discount_percentage' => NULL,
            ),
            13 => 
            array (
                'id' => 20,
                'course_category_id' => 10,
                'instructor_id' => 6,
                'image' => 'images/vv89Ya2Ti6bVNjl0WfcexPaohikbrddfksF7tSjo.jpg',
                'title' => 'Smart Contract Development dengan Ethereum',
                'slug' => 'smart-contract-ethereum',
                'description' => 'Belajar membangun smart contract di blockchain Ethereum.',
                'prerequisites' => 'Dasar pemrograman.',
                'goals' => 'Mampu membuat smart contract menggunakan Solidity.',
                'duration' => 220,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:13:22',
                'discount_percentage' => NULL,
            ),
            14 => 
            array (
                'id' => 19,
                'course_category_id' => 10,
                'instructor_id' => 6,
                'image' => 'images/ttBkq6Nw8dD1XpO2pet3Cy4YE1Vq1oKRHPTUbjc4.jpg',
                'title' => 'Blockchain dan Cryptocurrency: Dasar hingga Lanjutan',
                'slug' => 'blockchain-cryptocurrency',
                'description' => 'Pelajari dasar-dasar blockchain dan implementasi cryptocurrency.',
                'prerequisites' => 'Tidak ada, cocok untuk pemula.',
                'goals' => 'Memahami cara kerja blockchain dan mata uang kripto.',
                'duration' => 200,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:10:28',
                'discount_percentage' => 5.0,
            ),
            15 => 
            array (
                'id' => 24,
                'course_category_id' => 12,
                'instructor_id' => 6,
                'image' => 'images/J8ooTUAlomgpsA3AQ2SWVk6rBmsE5ly4TKgnYh7d.jpg',
                'title' => 'Membangun Sistem IoT dengan Raspberry Pi',
                'slug' => 'membangun-iot-raspberry-pi',
                'description' => 'Pelajari cara membuat sistem berbasis IoT menggunakan Raspberry Pi.',
                'prerequisites' => 'Dasar pemrograman Python.',
                'goals' => 'Mampu menghubungkan perangkat IoT dengan cloud.',
                'duration' => 220,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:07:06',
                'discount_percentage' => 5.0,
            ),
            16 => 
            array (
                'id' => 23,
                'course_category_id' => 12,
                'instructor_id' => 6,
                'image' => 'images/3W6nxFkRhH0U23cnV497jCQx2ZCZIwGWksBIMfx6.jpg',
            'title' => 'Internet of Things (IoT) dengan Arduino',
                'slug' => 'iot-arduino',
                'description' => 'Pelajari cara membuat perangkat IoT menggunakan Arduino.',
                'prerequisites' => 'Dasar pemrograman.',
                'goals' => 'Mampu membangun proyek IoT sederhana dengan Arduino.',
                'duration' => 200,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:04:15',
                'discount_percentage' => NULL,
            ),
            17 => 
            array (
                'id' => 22,
                'course_category_id' => 11,
                'instructor_id' => 8,
                'image' => 'images/CHD0wpKK4Df42PEWuA4e8yKzQQqGiBo4IiI3XLPQ.jpg',
                'title' => 'Desain Sistem UI/UX untuk Aplikasi Web',
                'slug' => 'desain-sistem-uiux-aplikasi-web',
                'description' => 'Pelajari cara mendesain UI/UX untuk aplikasi web secara profesional.',
                'prerequisites' => 'Pemahaman dasar desain.',
                'goals' => 'Mampu membuat desain UI/UX berbasis pengalaman pengguna.',
                'duration' => 200,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:36:29',
                'discount_percentage' => NULL,
            ),
            18 => 
            array (
                'id' => 27,
                'course_category_id' => 14,
                'instructor_id' => 9,
                'image' => 'images/9jxKaYN5eTIt6AuOslL7qx1DLBKqNy2yS9FFpfDW.jpg',
                'title' => 'Manajemen Basis Data dengan PostgreSQL',
                'slug' => 'manajemen-basis-data-postgresql',
                'description' => 'Belajar konsep manajemen basis data dengan PostgreSQL.',
                'prerequisites' => 'Dasar SQL.',
                'goals' => 'Mampu mengelola database menggunakan PostgreSQL.',
                'duration' => 180,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:48:03',
                'discount_percentage' => NULL,
            ),
            19 => 
            array (
                'id' => 26,
                'course_category_id' => 13,
                'instructor_id' => 9,
                'image' => 'images/ghdaehzPkK6xM9Xl36jsIcisXrIplWh2bY8m5Jpf.jpg',
                'title' => 'Game Development dengan Unreal Engine',
                'slug' => 'game-development-unreal-engine',
                'description' => 'Pelajari pengembangan game menggunakan Unreal Engine.',
                'prerequisites' => 'Pemahaman dasar pemrograman.',
                'goals' => 'Mampu membuat game berbasis Unreal Engine.',
                'duration' => 260,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:47:17',
                'discount_percentage' => 5.0,
            ),
            20 => 
            array (
                'id' => 25,
                'course_category_id' => 13,
                'instructor_id' => 9,
                'image' => 'images/4xLwBr2Rvmstlkasajnov0SKuUk4EiXwrT5Gnb99.jpg',
                'title' => 'Pemrograman Game dengan Unity dan C#',
                'slug' => 'pemrograman-game-unity-csharp',
                'description' => 'Belajar membuat game dengan Unity dan bahasa pemrograman C#.',
                'prerequisites' => 'Dasar pemrograman.',
                'goals' => 'Mampu membangun game sederhana menggunakan Unity.',
                'duration' => 240,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:46:28',
                'discount_percentage' => NULL,
            ),
            21 => 
            array (
                'id' => 29,
                'course_category_id' => 15,
                'instructor_id' => 9,
                'image' => 'images/BHCz9qsZXlRMHkpH4lJKmev8mbBblbbk5zcaqDus.jpg',
                'title' => 'Software Testing & QA Automation',
                'slug' => 'software-testing-qa-automation',
                'description' => 'Pelajari teknik pengujian perangkat lunak dan otomatisasi QA.',
                'prerequisites' => 'Pemahaman dasar pemrograman.',
                'goals' => 'Mampu melakukan pengujian perangkat lunak dengan teknik manual dan otomatis.',
                'duration' => 190,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:45:34',
                'discount_percentage' => NULL,
            ),
            22 => 
            array (
                'id' => 28,
                'course_category_id' => 14,
                'instructor_id' => 9,
                'image' => 'images/BblY8ZYCDgkFtu2WbfeiN5GxDzEzuGQkj41J3oSM.jpg',
                'title' => 'Optimasi Query dan Indexing di MySQL',
                'slug' => 'optimasi-query-indexing-mysql',
                'description' => 'Pelajari cara meningkatkan performa database dengan query dan indexing yang efisien.',
                'prerequisites' => 'Pemahaman dasar SQL.',
                'goals' => 'Mampu mengoptimalkan database untuk performa tinggi.',
                'duration' => 200,
                'price' => 95000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:44:39',
                'discount_percentage' => 5.0,
            ),
            23 => 
            array (
                'id' => 30,
                'course_category_id' => 15,
                'instructor_id' => 8,
                'image' => 'images/2hUaO0mAPQamO9Yhpp6oP8iIF1xpbNi0Z0xGeB20.jpg',
                'title' => 'Pengujian Keamanan Aplikasi Web',
                'slug' => 'pengujian-keamanan-aplikasi-web',
                'description' => 'Belajar metode pengujian keamanan pada aplikasi web.',
                'prerequisites' => 'Pemahaman dasar keamanan siber.',
                'goals' => 'Mampu melakukan penetration testing terhadap aplikasi web.',
                'duration' => 210,
                'price' => 95000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:33:49',
                'discount_percentage' => 5.0,
            ),
            24 => 
            array (
                'id' => 8,
                'course_category_id' => 4,
                'instructor_id' => 6,
                'image' => 'images/MM7wdDFEF2AporEkqFFCCpE13JM6mk7mNIGO5ffo.jpg',
                'title' => 'Membangun Microservices dengan Spring Boot',
                'slug' => 'microservices-spring-boot',
                'description' => 'Belajar konsep microservices dan implementasinya menggunakan Spring Boot.',
                'prerequisites' => 'Dasar pemrograman Java.',
                'goals' => 'Mampu membangun aplikasi berbasis microservices.',
                'duration' => 200,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:24:44',
                'discount_percentage' => NULL,
            ),
            25 => 
            array (
                'id' => 4,
                'course_category_id' => 2,
                'instructor_id' => 6,
                'image' => 'images/eSo6gZUD4FjE4P6pVt79EqRFukJkVlN95RwlLghC.jpg',
                'title' => 'Membangun Website dengan HTML, CSS, dan JavaScript',
                'slug' => 'membangun-website-html-css-js',
                'description' => 'Pelajari cara membuat website dari nol menggunakan HTML, CSS, dan JavaScript.',
                'prerequisites' => 'Tidak ada, cocok untuk pemula.',
                'goals' => 'Mampu membangun halaman web statis yang menarik.',
                'duration' => 120,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:26:28',
                'discount_percentage' => 10.0,
            ),
            26 => 
            array (
                'id' => 5,
                'course_category_id' => 3,
                'instructor_id' => 9,
                'image' => 'images/rWYtLFRqOzy1ZQsIQkvAnpsd1zHHr9aWXFPDhwND.jpg',
                'title' => 'Machine Learning untuk Pemula dengan Python',
                'slug' => 'machine-learning-pemula-python',
                'description' => 'Pengenalan dasar machine learning dengan Python dan pustaka scikit-learn.',
                'prerequisites' => 'Pemrograman dasar Python.',
                'goals' => 'Mampu memahami konsep machine learning dan menerapkan algoritma sederhana.',
                'duration' => 200,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:52:40',
                'discount_percentage' => NULL,
            ),
            27 => 
            array (
                'id' => 1,
                'course_category_id' => 1,
                'instructor_id' => 8,
                'image' => 'images/u7KXxElbfL6eLZhCHh8zUia1TvGEUXWPwIukmNOT.jpg',
                'title' => 'Dasar-Dasar Pemrograman dengan Python',
                'slug' => 'dasar-pemrograman-python',
                'description' => 'Pelajari konsep dasar pemrograman menggunakan Python dari nol.',
                'prerequisites' => 'Tidak ada, cocok untuk pemula.',
                'goals' => 'Memahami sintaks dasar Python dan mampu membuat program sederhana.',
                'duration' => 120,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:41:36',
                'discount_percentage' => 12.0,
            ),
            28 => 
            array (
                'id' => 2,
                'course_category_id' => 1,
                'instructor_id' => 8,
                'image' => 'images/9bEnvGSPnp3w8AxtgzWaXRf23ISoapgpPbnoE9OJ.jpg',
                'title' => 'Algoritma dan Struktur Data dengan Python',
                'slug' => 'algoritma-struktur-data-python',
                'description' => 'Pelajari konsep dasar algoritma dan struktur data dengan Python.',
                'prerequisites' => 'Dasar pemrograman Python.',
                'goals' => 'Mampu mengimplementasikan algoritma dan struktur data dalam Python.',
                'duration' => 150,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:42:28',
                'discount_percentage' => 50.0,
            ),
            29 => 
            array (
                'id' => 3,
                'course_category_id' => 2,
                'instructor_id' => 6,
                'image' => 'images/2VVUjQOyD3n7KMje0lHvaUwiL0Jb8GiyxRcD2hoT.jpg',
                'title' => 'Full-Stack Web Development dengan Next.js dan MySQL',
                'slug' => 'fullstack-web-nextjs-mysql',
                'description' => 'Belajar membangun aplikasi web full-stack dengan Next.js dan MySQL.',
                'prerequisites' => 'Pemahaman dasar HTML, CSS, dan JavaScript.',
                'goals' => 'Mampu membangun aplikasi web dengan Next.js dan menghubungkannya dengan MySQL.',
                'duration' => 180,
                'price' => 100000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => NULL,
                'updated_at' => '2025-03-19 06:28:08',
                'discount_percentage' => 25.0,
            ),
            30 => 
            array (
                'id' => 33,
                'course_category_id' => 2,
                'instructor_id' => 11,
                'image' => 'images/arUQzEnCpt3BgoijRFYOmzXX6CLLT5PuebwVCGfF.png',
                'title' => 'ReactJS Tutorial for Beginners',
                'slug' => 'reactjs-tutorial-for-beginners',
                'description' => 'React is an open source javascript library for building user interfaces.
React is a project created and maintained by Facebook.
React has more than a 100 thousand stars on GitHub and a huge community behind it.
React has become increasingly 
popular among developers and is also one of the most sought out skill-sets by companies right now.',
                'prerequisites' => 'HTML, CSS , Javascript',
                'goals' => 'React has a component based architecture. This lets you break down your application into small encapsulated parts which can then be composed to make more complex UI.
React is declarative.
React will make it painless for you to create complex UIs by abstracting away the difficult parts. 
React will handle efficiently updating and rendering just the right components in your application when your data changes. 
DOM updates which is one of the more expensive operations is handled gracefully in React.',
                'duration' => NULL,
                'price' => 120000.0,
                'level' => 'beginner',
                'status' => 1,
                'created_at' => '2025-04-12 02:50:10',
                'updated_at' => '2025-04-12 02:50:10',
                'discount_percentage' => 0.0,
            ),
        ));
        
        
    }
}